# Generated by Django 3.1.4 on 2020-12-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Animes', '0003_auto_20201210_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManejadorUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('usuario', models.CharField(max_length=100, unique=True, verbose_name='Usuario')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('correo', models.EmailField(default=None, max_length=254, unique=True, verbose_name='Correo Electronico')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('staff', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=True)),
                ('Selection_Animes', models.ManyToManyField(to='Animes.Anime', verbose_name='Anime')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
